# oa_config_test.R
#
# oa_config_r SWIG wrapper test.
#
# Author: Derek Huang
# Copyright: MIT License
#
# This only tests the built oa_config_r shared object as the oa_config_r.R
# wrapper generated by SWIG is unusable in its current form.
#

# TODO: move the shared oa.* code out into the oa.testutils package

##
# Exit the running R script with the given exit code.
#
# This function does not save the current R workspace.
#
# Arguments:
#   status      Exit code
#
oa.exit <- function(status = 0) {
  quit("no", status)
}

##
# Load a shared object given its filename stem.
#
# The extension is automatically determined using .Platform$dynlib.ext.
#
# Arguments:
#   name        DSO file name stem
#
oa.loadLibrary <- function(name) {
  dyn.load(paste(name, .Platform$dynlib.ext, sep = ""))
}

##
# Run a single named test.
#
# The test function must take no parameters and return TRUE on success, FALSE
# on error, and is encouraged to print meaningful test messages.
#
# Arguments:
#   name        Test name
#   test        Test function
#
# Returns:
#   0 on success, 1 on failure; interpret as number of test failures
#
oa.runTest <- function(name, test) {
    cat("[ RUN      ]", name, fill = TRUE)
  if (test()) {
    cat("[     PASS ]", name, fill = TRUE)
    return(0)
  } else {
    cat("[     FAIL ]", name, fill = TRUE)
    return(1)
  }
}

##
# Run a list of named tests.
#
# The tests object must be a named vector where each value is a function that
# returns TRUE on success, FALSE on error, and wil be invoked by runTest().
#
# Arguments:
#   tests         Named vector of tests
#
# Returns:
#   Number of failed tests
#
oa.runTests <- function(tests) {
  # test names
  test_names <- names(tests)
  # default action is to run all test cases
  n_tests <- length(tests)
  cat("Running", n_tests, "test cases...", fill = TRUE)
  # no tests to run
  if (n_tests == 0) {
    cat("No tests to run!", fill = TRUE)
    return(0)
  }
  # count failed
  failed <- 0
  for (i in 1:n_tests)
    failed <- failed + oa.runTest(test_names[i], tests[[i]])
  # percentage pass
  pass_pct <- 100 * (1 - failed / n_tests)
  # report pass/fail + return number of failed
  cat(
    pass_pct,
    "% tests passed, ",
    failed,
    " tests failed out of ",
    n_tests,
    sep = "",
    fill = TRUE
  )
  return(failed)
}

##
# Standard main function for an R unit test script.
#
# This function parses incoming command-line arguments to determine the mode of
# operation and will run the tests specified in the named vector of tests using
# oa.runTests(). The -l, --list-tests argument causes the names of the tests to
# be printed, while -t, --test-case is used to specify a single test to run.
#
# Arguments:
#   argv          Command-line arguments to parse
#   desc          Text to display as part of usage printed for -h, --help
#   tests         Named vector of tests to run
#
oa.testMain <- function(
  argv = commandArgs(trailingOnly = TRUE),
  desc = "",
  tests = c()
) {
  # obtain R basename + file path index
  r_path <- basename(commandArgs()[1])
  file_i <- grep("--file=", commandArgs())
  # if NA, use "<stdin>", else strip --file= prefix + convert to base name
  if (is.na(file_i)) {
    file_name <- "<stdin>"
  } else {
    file_name <- basename(substring(commandArgs()[file_i], 8))
  }
  # usage description
  usage_line <- paste("Usage:", r_path, file_name, "[-h] [-l] [-t TEST_CASE]")
  # default description if desc is empty
  if (desc == "")
    desc <- "R test runner."
  # options description with trailing newline
  opts_help <- r"(Options:
  -h, --help                    Print this usage
  -l, --list-tests              List the names of all available tests
  -t, --test-case <name>        Name of test case to run
)"
  # number of arguments
  argc <- length(argv)
  # test names
  test_names <- names(tests)
  # iterate through arguments
  for (i in 1:argc) {
    # break if no more arguments, e.g. if argv is empty
    if (is.na(argv[i]))
      break
    # -h, --help
    if (argv[i] == "-h" || argv[i] == "--help") {
      cat(usage_line, "\n\n", desc, "\n\n", opts_help, sep = "")
      oa.exit()
    # -l, --list-tests
    } else if (argv[i] == "-l" || argv[i] == "--list-tests") {
      # print the test names + exit
      for (i in 1:length(test_names))
        cat(test_names[i], fill = TRUE)
      oa.exit()
    # -t, --test-case
    } else if (argv[i] == "-t" || argv[i] == "--test-case") {
      # need to have another argument available
      if (i == argc)
        stop(paste("Error: -t, --test-case missing required test name"))
      # look up test case
      test_name <- argv[i + 1]
      test_case <- tests[[test_name]]
      if (is.null(test_case))
        stop(paste("Error: No test named", test_name, "in list of tests"))
      # ok, run test and return 0 (success) or 1 (failure)
      oa.exit(oa.runTest(test_name, test_case))
    # ignore --no-echo, --no-restore, --file=<script path> added by Rscript
    } else if (
      argv[i] == "--no-echo" ||
      argv[i] == "--no-restore" ||
      substr(argv[i], 1, 7) == "--file="
    ) {
    # ignore unknown options in case we haven't fully covered them
    } else {
      cat("Warning: Unknown option \"", argv[i], "\"", sep = "", fill = TRUE)
    }
  }
  # default action is to run all test cases
  oa.exit(ifelse(oa.runTests(tests), 1, 0))
}

# TODO: document
oa.namedTests = function(...) {
  tests <- c(...)
  n_tests = length(tests)
  # no tests
  if (!n_tests)
    return(NULL)
  # copy tests
  # note: R uses copy-on-write so this isn't copied just yet
  named_tests <- tests
  # convert to names
  test_names <- NULL
  for (i in 1:n_tests)
    test_names[i] = deparse(quote(tests[[i]]))
  print(test_names)
  # assign names to named_tests and return
  setNames(named_tests, test_names)
  return(named_tests)
}

# load shared object
oa.loadLibrary("oa_config_r")

# TODO: parse commandArgs() CLI args for individual test running

# test that library_dir() and data_dir() are the same
testLibraryDataDirs <- function() {
  # note: SWIG adds an extra argument that we can ignore
  lib_dir <- .Call("R_swig_library_dir", "")
  data_dir <- .Call("R_swig_data_dir", "")
  # check
  if (lib_dir == data_dir) {
    return(TRUE)
  } else {
    msg <- "library_dir() != data_dir(): ["
    msg <- paste(msg, lib_dir, " != ", data_dir, "]", sep = "")
    cat(msg, fill = TRUE)
    return(FALSE)
  }
}

# named vector of tests to run
tests = c(testLibraryDataDirs = testLibraryDataDirs)

# main
oa.testMain(desc = "oa_config unit tests.", tests = tests)
