# oa_config_test.R
#
# oa_config_r SWIG wrapper test.
#
# Author: Derek Huang
# Copyright: MIT License
#
# This only tests the built oa_config_r shared object as the oa_config_r.R
# wrapper generated by SWIG is unusable in its current form.
#

# load shared object
dyn.load(paste("oa_config_r", .Platform$dynlib.ext, sep = ""))

# TODO: parser commandArgs() CLI args for individual test running

# test library_dir() and data_dir() are the same
# note: SWIG adds an extra argument that we can ignore
lib_dir <- .Call("R_swig_library_dir", "")
cat("library_dir():", lib_dir, fill = TRUE)
data_dir <- .Call("R_swig_data_dir", "")
cat("data_dir():", data_dir, fill = TRUE)
# check
if (lib_dir == data_dir) {
  cat("OK", fill = TRUE)
} else {
  msg <- "library_dir() != data_dir(): ["
  msg <- paste(msg, lib_dir, " != ", data_dir, "]", sep = "")
  stop(msg)
}
