# oa_config_test.R
#
# oa_config_r SWIG wrapper test.
#
# Author: Derek Huang
# Copyright: MIT License
#
# This only tests the built oa_config_r shared object as the oa_config_r.R
# wrapper generated by SWIG is unusable in its current form.
#

# load testutils package
library(oa.testutils)

# load shared object
oa.tu_load("oa_config_r")

# test that library_dir() and data_dir() are the same
test_library_data_dirs <- function() {
  # note: SWIG adds an extra argument that we can ignore
  lib_dir <- .Call("R_swig_library_dir", "")
  data_dir <- .Call("R_swig_data_dir", "")
  # check
  if (lib_dir == data_dir) {
    return(TRUE)
  } else {
    msg <- "library_dir() != data_dir(): ["
    msg <- paste(msg, lib_dir, " != ", data_dir, "]", sep = "")
    cat(msg, fill = TRUE)
    return(FALSE)
  }
}

# named vector of tests to run
tests = c(test_library_data_dirs = test_library_data_dirs)

# main
oa.tu_exit(oa.tu_main(desc = "oa_config unit tests.", tests = tests))
