"""SWIG-specific Python module providing better C++ scoped enum support.

This module should only be used via ``%pythoncode`` directive in SWIG.

.. codeauthor:: Derek Huang <djh458@stern.nyu.edu>
"""


def _to_pascal_case(s: str) -> str:
    """Convert a string into PascalCase.

    The first character is capitalized and any ``_[a-zA-Z]`` is converted into
    an uppercase version of the aforementioned two-character sequence.

    The string is expected to contain only alphanumeric characters and "_". In
    short, it must be a valid identifier before this function is called.
    """
    # indicate if we saw an underscore and need to uppercase next char. this
    # is initially set to True since the first character is capitalized
    make_upper = True
    # final string's length-1 components
    comps = []
    # iterate
    for c in s:
        # skip underscores. we'll need to capitalize next char
        if c == "_":
            make_upper = True
            continue
        # if make_upper is True, uppercase
        if make_upper:
            comps.append(c.upper())
            make_upper = False
        # otherwise copy
        else:
            comps.append(c)
    # return completed string
    return "".join(comps)


def _export_enum_class(
    cxx_name: str,
    py_name: str = "",
    doc: str = "",
    strip_prefix: str = ""
) -> None:
    """Convert SWIG-wrapped scoped enum members into an enum class.

    When SWIG wraps C++ scoped enums for Python members with the format
    ``<enum>_<member>`` are added to the SWIG Python wrapper module. These
    members are not very syntactically pretty and lose the scoping associated
    with C++ scoped enums. This function converts any members of the form
    ``<enum>_<member>`` to an ``enum.Enum`` class named ``<enum>``, with all
    the enum members renamed to be upper case, optionally with the enum member
    prefix stripped out, e.g. ``"k"`` or ``"k_"``, depending on how the SWIG
    ``%rename`` directive was used with the enum members.

    This function should be used via ``OA_EXPORT_ENUM_CLASS()`` as follows:

    .. code::

       // ensure enum types are in PascalCase for Python
       %rename("%(camelcase)s", %$isenum) "";
       // ensure enum members are in snake_case for Python
       %rename("%(undercase)s", %$isenumitem) "";

       // process header containing scoped enums, e.g. oa::time::Tenors, whose
       // members are wrapped by SWIG as Tenors_* module constants, e.g.
       // Tenors_k_months, due to the above %rename directives
       %include "oa/time/enums.h"

       // export the enum class into Python as an enum.Enum. the Tenors_*
       // members are replaced the "Tenors" enum.Enum in the SWIG wrapper
       OA_EXPORT_ENUM_CLASS(oa::time::Tenors, strip_prefix="k_")

    .. note::

       The SWIG-wrapped module members for the scoped enum members will be
       removed before the function returns and will no longer be accessible.

    Parameters
    ----------
    cxx_name : str
        C++ fully-qualified scoped enum name to export as the ``py_name`` enum
        class with corresponding SWIG-generated ``<enum>_<member>`` members
    py_name : str, default=""
        Enum class name + ``<enum>`` prefix for each ``<enum>_<member>`` member
        generated by SWIG for the C++ scoped enum given by ``cxx_name``. If
        empty, the unqualified type portion of ``cxx_name`` is processed by
        ``_to_pascal_case()`` to produce the PascalCase Python enum class name.
    doc : str, default=""
        Enum class docstring. If empty, a default docstring containing
        ``cxx_name`` will be used to make it clear which C++ enum is exported.
    strip_prefix : str, default=""
        Prefix to remove from each C++ scoped enum member after ``%rename``
    """
    import enum
    import sys
    # module reference
    mod = sys.modules[__name__]
    # if py_name empty use _to_pascal_case()
    if not py_name:
        py_name = _to_pascal_case(cxx_name.split("::")[-1])
    # get all SWIG-wrapped members
    enum_mems = [x for x in dir(mod) if x.startswith(f"{py_name}_")]
    # default docstring if empty
    if not doc:
        doc = f"Enum class representing the members of {cxx_name}."
    # create enum class
    enum_class = enum.Enum(
        py_name,
        [
            # keep only the stripped <member> portion of <enum>_<member>
            (
                mem.replace(f"{py_name}_{strip_prefix}", "", 1).upper(),
                getattr(mod, mem)
            )
            for mem in enum_mems
        ]
    )
    # set docstring + C++ type name member
    # note: _cxx_type_name is hidden in the dirs() view but is present in the
    # __dict__ member so directly accessing the attribute works
    enum_class.__doc__ = doc
    enum_class._cxx_type_name = cxx_name
    # create enum class as a module attribute + remove SWIG-wrapped members
    setattr(mod, py_name, enum_class)
    for mem in enum_mems:
        delattr(mod, mem)
